### PR TITLE
fix the path problem & improve the structure

### PR DESCRIPTION
**Pull request by yuchengdong**

### CODE REVIEW

**Comment by yuchengdong** [comment]
@jarrodmillman @matthew-brett @rossbar Hi guys, I have this problem where I have nosetests of testing file totally running on my computer, but it fails the TravisCI checks here. Can you please take a look and maybe give me some hints about how to solve the issue?

**Comment by matthew-brett** [comment]
It looks like 'scenes' is not on the the Python PATH.  You could try setting the PYTHONPATH variable with something like:

```
export PYTHONPATH=$PWD/code/utils
```

in your travis.yml file, before running nosetests.

**Comment by yuchengdong** [comment]
@matthew-brett Hi Matt, thanks for replying. 
So we did change to .travis.yml
script:
   - make coverage
+ - export PYTHONPATH=$PWD/code/utils
and it didn't work

**Comment by matthew-brett** [comment]
Right - you have to run that command before you run the code doing `import scenes`.

**Comment by yuchengdong** [comment]
@matthew-brett Hi Matt, thank you so much for helping, we finally fix the issue. Have a good night!

**Pull request merged**
