### PR TITLE
Wordlist

### PR DESCRIPTION
**Pull request by ariaaay**

### CODE REVIEW

**Comment by cxmo** [comment]
@ariaaay error: FileNotFoundError: [Errno 2] No such file or directory: '../../../description_pp/design_matrix_1.npy'

**Comment by ariaaay** [comment]
Yeah I am working on it.

**Comment by ariaaay** [comment]
@cxmo the travis CI works now. Could you merge it for me? Thanks!

**Comment by cxmo** [comment]
@ariaaay yep

**Pull request merged**
